spring:
  profiles: local

server:
  port: 6000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

auth0:
  domain: local-auth0.com
  issuer: http://localhost:8080/
  audience: local-api
  token-validation:
    enabled: false

redis:
  host: localhost
  port: 6379
