spring:
  config:
    activate:
      on-profile: local
  # Security Configuration for OAuth2 + JWT
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://noobiedev.us.auth0.com/
          jwk-set-uri: https://noobiedev.us.auth0.com/.well-known/jwks.json
          audiences: https://noobiedev.us.auth0.com/api/v2/

server:
  port: 6000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

# Auth0 Configuration
auth0:
  domain: noobiedev.us.auth0.com
  issuer: https://noobiedev.us.auth0.com/
  audience: https://noobiedev.us.auth0.com/api/v2/
  jwks-uri: https://noobiedev.us.auth0.com/.well-known/jwks.json
  token-validation:
    enabled: true
    require-issuer: true
    require-audience: true

redis:
  host: localhost
  port: 6379
