spring:
  config:
    activate:
      on-profile: test

eureka:
  instance:
    hostname: discovery-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8762/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 45000